version: 2
jobs:
  welcome/run:
    docker:
      - image: circleci/welcome-config-image:0.1.40-b28e6fe
    steps:
      - run:
          command: welcome_message.sh
          name: Welcome and basics to get you started
      - run:
          command: common_env_vars.sh
          name: Built-in environment variables for your project
      - run:
          command: next_steps.sh
          name: Next steps to customize your pipeline
workflows:
  Welcome:
    jobs:
      - welcome/run
  version: 2